module.exports = {
  "UPDATE_YAML": 'UPDATE_YAML',
  "SET_CURRENT_TAB":"SET_CURRENT_TAB",
  "SELECT_NODE":"SELECT_NODE",
  "UPDATE_FLOWCHART":"UPDATE_FLOWCHART",
  "UPDATE_YAML_STRING":"UPDATE_YAML_STRING"
}