import { Settings } from "../../redux/settings/settings.types"

export const status_success_response = {
  jina: {
    jina: "1.0.13",
    "jina-proto": "0.0.79",
    "jina-vcs-tag": "",
    libzmq: "4.3.4",
    pyzmq: "1.20.1",
    protobuf: "3.15.6",
    "proto-backend": "cpp",
    grpcio: "1.36.1",
    pyyaml: "5.4.1",
    python: "3.7.10",
    platform: "Linux",
    "platform-release": "4.19.121-linuxkit",
    "platform-version": "#1 SMP Thu Jan 21 15:36:34 UTC 2021",
    architecture: "x86_64",
    processor: "",
    "jina-resources": "/usr/local/lib/python3.7/site-packages/jina/resources",
  },
  envs: {
    JINA_ARRAY_QUANT: "(unset)",
    JINA_BINARY_DELIMITER: "(unset)",
    JINA_CONTRIB_MODULE: "(unset)",
    JINA_CONTRIB_MODULE_IS_LOADING: "(unset)",
    JINA_CONTROL_PORT: "(unset)",
    JINA_DEFAULT_HOST: "(unset)",
    JINA_DISABLE_UVLOOP: "(unset)",
    JINA_EXECUTOR_WORKDIR: "(unset)",
    JINA_FULL_CLI: "(unset)",
    JINA_IPC_SOCK_TMP: "(unset)",
    JINA_LOG_CONFIG: "(unset)",
    JINA_LOG_ID: "(unset)",
    JINA_LOG_LEVEL: "(unset)",
    JINA_LOG_NO_COLOR: "(unset)",
    JINA_LOG_WORKSPACE: "/tmp/jinad/7238f764-d238-4645-9136-530cc3feccc6",
    JINA_POD_NAME: "(unset)",
    JINA_RAISE_ERROR_EARLY: "(unset)",
    JINA_RANDOM_PORTS: "(unset)",
    JINA_RANDOM_PORT_MAX: "(unset)",
    JINA_RANDOM_PORT_MIN: "(unset)",
    JINA_SOCKET_HWM: "(unset)",
    JINA_VCS_VERSION: "",
    JINA_WARN_UNNAMED: "(unset)",
    JINA_WORKSPACE: "(unset)",
  },
  used_memory: "62.0 KB",
}

export const settings: Settings = {
  jinadHost: "http://localhost",
  jinadPort: "5000",
  gatewayHost: "http://localhost",
  gatewayPort: "8000",
  log: "/stream/log",
  profile: "/stream/profile",
  yaml: "/data/yaml",
  shutdown: "/action/shutdown",
  ready: "/status/ready",
}
